import type { Metadata } from "next"
import { Fira_Code } from "next/font/google"
import { ThemeProvider } from "@/providers/theme-provider"
import { AppProvider } from "@/providers/app-provider"
import { LayoutProps } from "@/@types"
import { cn } from "@/lib/utils"
import "./globals.css"
import { Header } from "@/components/header"

const firaCode = Fira_Code({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Sushi Memory Game",
  description: "Generated by create next app",
}

export default function RootLayout({ children, }: Readonly<LayoutProps>) {
  return (
    <html lang="en">
      <body className={cn(firaCode.className, "antialiased")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <AppProvider>
            <Header />
            {children}
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
